query FindProfile{
    findProfile{
        username
        email
        displayName
        avatar
        bio
        isTotpEnabled
        notificationSettings{
            siteNotifications
            telegramNotifications
        }
    }
}