import type {Metadata} from "next";

import {GeistSans} from 'geist/font/sans'
import "./globals.css";
import "../styles/themes.css"
import {ApolloClientProvider} from "@/providers/ApolloClientProvider";
import {NextIntlClientProvider} from "next-intl";
import {getLocale, getMessages} from "next-intl/server";
import {ThemeProvider} from "@/providers/ThemeProvider";
import {ToastProvider} from "@/providers/ToastProvider";
import ColorSwitcher from "@/components/ui/elements/ColorSwitcher";


export const metadata: Metadata = {
    title: "Home page",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    const local = await getLocale();
    const messages = await getMessages();
    return (
        <html lang={local} suppressHydrationWarning>
        <body
            className={GeistSans.variable}
        >
        <ApolloClientProvider>
            <NextIntlClientProvider messages={messages}>
                <ColorSwitcher/>
                <ThemeProvider attribute={'class'}
                               defaultTheme={'dark'}
                               disableTransitionOnChange
                >

                    <ToastProvider/>
                    {children}
                </ThemeProvider>
            </NextIntlClientProvider>
        </ApolloClientProvider>
        </body>
        </html>
    );
}
